name: alkhalafsheep
description: MatrixClouds.com new project alkhalafSheep

version: 2.0.3+4

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  json_serializable: ^6.7.1
  provider: ^6.1.1
  dio: ^5.4.0
  geocoding:
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  easy_localization: ^3.0.3
  awesome_dialog: ^3.2.0
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  path_provider: ^2.1.1
  another_flushbar: ^1.12.30
  social_media_buttons: ^1.0.0
  url_launcher: ^6.2.2
  flutter_widget_from_html_core: ^0.14.10+1
  getwidget: ^4.0.0
#  getflutter: ^1.1.3
  #todo ios configuration for map
  #  google_map_location_picker: ^4.1.2+1
  google_fonts: ^6.1.0
  #todo ios configuration for flutter_local_notifications
  flutter_local_notifications: ^16.3.0
  #todo proguard -keep class com.dexterous.** { *; }
  #todo ios configuration for firebase_messaging
  firebase_messaging: ^14.7.9
  #  firebase_core: ^0.5.0+1
#  esys_flutter_share: ^1.0.2
  # pull_to_refresh: ^1.6.3
  swipeable_page_route: ^0.4.1
  steps_indicator: ^1.3.0
  avatar_glow: ^3.0.1
  fluttertoast: ^8.2.4
  introduction_screen: ^3.1.12
  google_maps_flutter: ^2.5.1
  #  location: ^3.2.1
  #  flutter_google_places: ^0.2.6
  permission_handler: ^6.1.3
#  google_maps_place_picker: ^2.1.0-nullsafety.3
  google_maps_place_picker_mb: ^3.1.2
  geolocator: ^10.1.0

  # youtube_player_flutter: ^8.0.0

# dependency_overrides:
#   flutter_inappwebview: ^5.3.2

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.3
#
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/img/logo_white_bk_no_alpha.png"
#flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  assets:
    - resources/langs/ar.json
    - resources/langs/en.json
    - assets/img/
    - assets/holder/
